// Code generated by "stringer -type=Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Identifier-1]
	_ = x[IntegerLiteral-2]
	_ = x[StringLiteral-3]
	_ = x[FloatLiteral-4]
	_ = x[CharacterLiteral-5]
	_ = x[KwFn-6]
	_ = x[KwDo-7]
	_ = x[KwVar-8]
	_ = x[KwMut-9]
	_ = x[KwReturn-10]
	_ = x[KwEnd-11]
	_ = x[KwChar-12]
	_ = x[KwInt-13]
	_ = x[KwBool-14]
	_ = x[KwNull-15]
	_ = x[KwUnit-16]
	_ = x[KwString-17]
	_ = x[KwFloat-18]
	_ = x[KwIf-19]
	_ = x[KwThen-20]
	_ = x[KwElse-21]
	_ = x[KwStruct-22]
	_ = x[KwIs-23]
	_ = x[KwImportC-24]
	_ = x[KwWhile-25]
	_ = x[KwStop-26]
	_ = x[KwDefer-27]
	_ = x[KwEnum-28]
	_ = x[Plus-29]
	_ = x[Minus-30]
	_ = x[Star-31]
	_ = x[Slash-32]
	_ = x[Equal-33]
	_ = x[EqualEqual-34]
	_ = x[Bang-35]
	_ = x[BangEqual-36]
	_ = x[Less-37]
	_ = x[LessEqual-38]
	_ = x[Greater-39]
	_ = x[GreaterEqual-40]
	_ = x[Arrow-41]
	_ = x[Modulo-42]
	_ = x[Pipe-43]
	_ = x[LogicalOr-44]
	_ = x[LogicalAnd-45]
	_ = x[Ampersand-46]
	_ = x[Caret-47]
	_ = x[Tilde-48]
	_ = x[PlusEqual-49]
	_ = x[MinusEqual-50]
	_ = x[StarEqual-51]
	_ = x[SlashEqual-52]
	_ = x[ModuloEqual-53]
	_ = x[CaretEqual-54]
	_ = x[PipeEqual-55]
	_ = x[AmpersandEqual-56]
	_ = x[PlusPlus-57]
	_ = x[MinusMinus-58]
	_ = x[LessLess-59]
	_ = x[GreaterGreater-60]
	_ = x[LeftParen-61]
	_ = x[RightParen-62]
	_ = x[LeftBrace-63]
	_ = x[RightBrace-64]
	_ = x[Comma-65]
	_ = x[Semicolon-66]
	_ = x[Colon-67]
	_ = x[Dot-68]
	_ = x[LeftBracket-69]
	_ = x[RightBracket-70]
	_ = x[Newline-71]
	_ = x[EOF-72]
	_ = x[Error-73]
}

const _Kind_name = "unknownidentifierinteger_literalstring_literalfloat_literalcharacter_literalkw_fnkw_dokw_varkw_mutkw_returnkw_endkw_charkw_intkw_boolkw_nullkw_unitkw_stringkw_floatkw_ifkw_thenkw_elsekw_structkw_iskw_importkw_whilekw_stopkw_deferkw_enumplusminusstarslashequalequal_equalbangbang_equallessless_equalgreatergreater_equalarrowmodulopipelogical_orlogical_andampersandcarettildeplus_equalminus_equalstar_equalslash_equalmodulo_equalcaret_equalpipe_equalampersand_equalplus_plusminus_minusless_lessgreater_greaterleft_parenright_parenleft_braceright_bracecommasemicoloncolondotleft_bracketright_bracketnewlineeoferror"

var _Kind_index = [...]uint16{0, 7, 17, 32, 46, 59, 76, 81, 86, 92, 98, 107, 113, 120, 126, 133, 140, 147, 156, 164, 169, 176, 183, 192, 197, 206, 214, 221, 229, 236, 240, 245, 249, 254, 259, 270, 274, 284, 288, 298, 305, 318, 323, 329, 333, 343, 354, 363, 368, 373, 383, 394, 404, 415, 427, 438, 448, 463, 472, 483, 492, 507, 517, 528, 538, 549, 554, 563, 568, 571, 583, 596, 603, 606, 611}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
